#!/usr/bin/env python

"""Run the Binaural Beat Generator CLI."""
import sys

from binaural_generator.cli import main

if __name__ == "__main__":
    if sys.argv[0].endswith("-script.pyw"):
        sys.argv[0] = sys.argv[0][:-11]
    elif sys.argv[0].endswith(".exe"):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
