name: Reusable Publish Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'
      repository:
        required: true
        type: string
    secrets:
      TWINE_PASSWORD:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.4.2
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Build and publish
        run: |
          uv build
          uv run twine check dist/*
          uv run twine upload --skip-existing --repository ${{ inputs.repository }} dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
