name: Publish to PyPi

on:
  push:
    branches: [ main ]

jobs:
  publish:
    uses: ./.github/workflows/publish-reusable.yml
    with:
      repository: pypi
    secrets:
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
