name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v5.4.2
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          uv sync --group dev

      - name: Run Pytest
        run: uv run pytest --run-performance
