name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install uv
          uv sync --group dev

      - name: Run Pytest
        run: source .venv/bin/activate && pytest --run-performance
